### PR TITLE
Update google_benchmark to v1.5.3

### PR DESCRIPTION
**Pull request by homalozoa**
1. Change google_benchmark version from v1.5.2 to v1.5.3. Because v1.5.2
   can not build with GCC 11
2. Removed shrink-tz-offset-size.patch because of this patch was merged in
google-benchmark repo.

Signed-off-by: Homalozoa <nx.tardis@gmail.com>

### CODE REVIEW

**Comment by clalancette** [comment]
Let's run CI with this and see how it looks:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14682/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9434/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12347/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14825/)

**Comment by clalancette** [comment]
I *think* that the CMake warnings on aarch64 and Windows are expected for the performance benchmarks, but I'm not sure.  @cottsay Could you take a look at this PR and the CI run and see if it makes sense to you?

**Comment by cottsay** [comment]
> Could you take a look at this PR and the CI run and see if it makes sense to you?

Yes, those warnings are expected with `AMENT_RUN_PERFORMANCE_TESTS`. This change looks good to me.

**Comment by clalancette** [comment]
> Yes, those warnings are expected with `AMENT_RUN_PERFORMANCE_TESTS`. This change looks good to me.

Thanks, appreciated.  Then I'll go ahead and merge this.

**Review by clalancette — APPROVED** [review]

**Pull request merged**
