### PR TITLE
Update to google benchmark version 1.6.1

### PR DESCRIPTION
**Pull request by clalancette**
This matches what is in Ubuntu 22.04, and also fixes a warning
when building in certain circumstances.

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

The soversion patch is no longer necessary, since the newer version seems to do the right thing (and we are currently checking out from a tag).

### CODE REVIEW

**Comment by clalancette** [comment]
Oh, interesting.  I didn't realize that this same branch was used for all of Foxy, Galactic, and Rolling.  This is obviously only directed at Rolling; if this is approved, I'll make separate branches for Foxy and Galactic.

**Comment by clalancette** [comment]
Here's regular CI, to show that it isn't breaking anything in the normal builds:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16277/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10898/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16643/)

Here's CI just on Linux amd64, running the benchmark tests:

* Linux Benchmark [Build Status](http://ci.ros2.org/job/ci_linux/16278/)

**Review by audrow — APPROVED** [review]
Looks good to me.

**Comment by clalancette** [comment]
Thanks!  Going ahead and merging this one.

**Pull request merged**
